name: Deploy to Google App Engine (Python 3.11)

on:
  push:
    branches:
      - main  # This deploys only when changes are pushed to the 'main' branch

jobs:
  deploy:
    name: Deploy to GAE
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Ensure Python 3.11 is used

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Authenticate with Google Cloud using the service account
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'  # Service Account Key JSON stored in GitHub Secrets

    # Set up Google Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Google Cloud Project ID stored in GitHub Secrets
        export_default_credentials: true

    # Optionally set the project using gcloud config
    - name: Configure gcloud project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Deploy the application to Google App Engine
    - name: Deploy to App Engine
      run: gcloud app deploy --quiet --project ${{ secrets.GCP_PROJECT_ID }}  # Deploy the app to App Engine
